name: Сборка и выгрузка

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]


jobs:
    build:
        name: Сборка
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Deploy via SFTP
              uses: milanmk/actions-file-deployer@master
              with:
                remote-protocol: "sftp"
                remote-host: "31.129.57.152"
                remote-user: "root"
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                remote-path: "fschool"