name: Сборка и выгрузка

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]


jobs:
    build:
        name: Сборка
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - run: pip install -r requirements.txt
            - run: python3 fortenzz.beget.tech/main.py

            - name: Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: fortenzz.beget.tech
                  username: fortenzz
                  password: 789964kOl)
                  local-dir: ./
                  exclude: |
                      /.git*
                      /.git*/
                      /.github*
                      /.github*/
                      /.vscode/
                      /README.md
                      /test*
                      /.venv*
                      /LICENCE
                      