name: Сборка и выгрузка

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]


jobs:
    build:
        name: Сборка
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                server: 31.129.57.152
                username: root
                password: uRQffuXQghAy
                protocol: ftps
                port: 22
                exclude: |
                    /.git
                    /.git*
                    /.git*/
                    /.github*
                    /.github*/
                    /.vscode/
                    /README.md
                    /test*
                    /.venv*
                    /LICENCE
                      