name: Сборка и выгрузка

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]


jobs:
    build:
        name: Сборка
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Deploy via SFTP
              uses: milanmk/actions-file-deployer@master
              with:
                remote-protocol: "sftp"
                remote-host: "89.223.31.54"
                remote-user: "root"
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                remote-path: "/root/fschool"
            
            - name: Отправка сообщения в группу telegram
              uses: colutius/Telegram-Msg@main
              with:
                chatid: ${{ secrets.TELEGRAM_TO }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                disable_notification: true
                message: |
                  Commit: ${{ github.event.commits[0].message }}
                  Branch: #${{ github.ref_name }}
                  Author: #${{ github.actor }} 
                button: true
                button_name: Посмотреть изменения
                button_url: https://github.com/${{ github.repository }}/commit/${{github.sha}}
                is_notify: false
                is_preview: false